---
{{- if .Values.stargate.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-k8ssandra-stargate-service
  labels:
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: graphql
      port: 8080
      protocol: TCP
    - name: authorization
      port: 8081
      protocol: TCP
    - name: rest
      port: 8082
      protocol: TCP
    - name: metrics
      port: 8085
      protocol: TCP
    - name: cql
      protocol: TCP
      port: 9042
  selector:
    app: {{ .Release.Name }}-k8ssandra-stargate
{{- end }}
